# : Manager [[[

[mgr]
cwd = { fg = "#171d1e" }

# Tab
tab_active = { fg = "#ffffff", bg = "#006876", bold = true }
tab_inactive = { fg = "#9eefff", bg = "#001f24" }
tab_width = 1

# Find
find_keyword = { fg = "#ba1a1a", bold = true, italic = true, underline = true }
find_position = { fg = "#ba1a1a", bold = true, italic = true }

# Marker
marker_copied = { fg = "#758cff", bg = "#758cff" }
marker_cut = { fg = "#dbe1ff", bg = "#dbe1ff" }
marker_marked = { fg = "#ba1a1a", bg = "#ba1a1a" }
marker_selected = { fg = "#535d7e", bg = "#535d7e" }

# Count
count_copied = { fg = "#0f1a37", bg = "#dbe1ff" }
count_cut = { fg = "#0f1a37", bg = "#dbe1ff" }
count_selected = { fg = "#ffffff", bg = "#535d7e" }

# Border
border_symbol = " "
border_style  = { fg = "#006876" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#ffffff", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#006876", fg = "#ffffff", bold = true }
normal_alt  = { bg = "#dbe4e6", fg = "#3f484a" }

# Select mode
select_main = { bg = "#4a6267", fg = "#ffffff", bold = true }
select_alt  = { bg = "#dbe4e6", fg = "#3f484a" }

# Unset mode
unset_main = { bg = "#535d7e", fg = "#ffffff", bold = true }
unset_alt  = { bg = "#dbe4e6", fg = "#3f484a" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#006876", bg = "#f5fafc" }
progress_error = { fg = "#ba1a1a", bg = "#f5fafc" }

# Permissions
permissions_t = { fg = "#96afb4" }
permissions_w = { fg = "#a6adc4" }
permissions_x = { fg = "#ed8080" }
permissions_r = { fg = "#4262ff" }
permissions_s = { fg = "#05d6ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#006876" }
active = { fg = "#535d7e", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#006876" }
value = { fg = "#171d1e" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#006876", bold = true, bg = "#f5fafc" }
inactive = { fg = "#4a6267", bg = "#f5fafc" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#006876", bg = "#ffffff" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#006876" }
title = {}
hovered = { fg = "#dbe1ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#f5fafc" }
cand = { fg = "#006876" }
rest = { fg = "#ffffff" }
desc = { fg = "#171d1e" }
separator = " ‚ñ∂ "
separator_style = { fg = "#171d1e" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#171d1e" }
run = { fg = "#171d1e" }
footer = { fg = "#ffffff", bg = "#4a6267" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#535d7e" }
title_warn = { fg = "#006876" }
title_error = { fg = "#ba1a1a" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#ffdad6" },
    { name = "*", is = "exec", fg = "#410002" },

    # Fallback
    { name = "*", fg = "#171d1e" },
    { name = "*/", fg = "#006876" },
]

# : ]]]
