# : Manager [[[

[mgr]
cwd = { fg = "#e2e2e2" }

# Tab
tab_active = { fg = "#4c2700", bg = "#ffb77a", bold = true }
tab_inactive = { fg = "#ffdcc2", bg = "#2e1500" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#c1cf63", bg = "#c1cf63" }
marker_cut = { fg = "#e0e7b1", bg = "#e0e7b1" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#c4cb97", bg = "#c4cb97" }

# Count
count_copied = { fg = "#191e00", bg = "#e0e7b1" }
count_cut = { fg = "#191e00", bg = "#e0e7b1" }
count_selected = { fg = "#4c2700", bg = "#c4cb97" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb77a" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#4c2700", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb77a", fg = "#4c2700", bold = true }
normal_alt  = { bg = "#474747", fg = "#c6c6c6" }

# Select mode
select_main = { bg = "#e3c0a5", fg = "#412c19", bold = true }
select_alt  = { bg = "#474747", fg = "#c6c6c6" }

# Unset mode
unset_main = { bg = "#c4cb97", fg = "#2d330d", bold = true }
unset_alt  = { bg = "#474747", fg = "#c6c6c6" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb77a", bg = "#393939" }
progress_error = { fg = "#ffb4ab", bg = "#393939" }

# Permissions
permissions_t = { fg = "#b66f39" }
permissions_w = { fg = "#7d8643" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#b2c33c" }
permissions_s = { fg = "#ff8429" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb77a" }
active = { fg = "#c4cb97", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb77a" }
value = { fg = "#e2e2e2" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ffb77a", bold = true, bg = "#131313" }
inactive = { fg = "#e3c0a5", bg = "#131313" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb77a", bg = "#4c2700" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb77a" }
title = {}
hovered = { fg = "#e0e7b1", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#393939" }
cand = { fg = "#ffb77a" }
rest = { fg = "#4c2700" }
desc = { fg = "#e2e2e2" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e2e2e2" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e2e2e2" }
run = { fg = "#e2e2e2" }
footer = { fg = "#412c19", bg = "#e3c0a5" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#c4cb97" }
title_warn = { fg = "#ffb77a" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e2e2e2" },
    { name = "*/", fg = "#ffb77a" },
]

# : ]]]
