[opener]
swayimg = [
  { run = 'swayimg "$@"', orphan = true, desc = "Open with swayimg", for = "unix" }
]

edit = [
  { run = 'nvim "$@"', block = true, desc = "Open with Neovim", for = "unix" }
]

open = [
  { run = 'xdg-open "$@"', desc = "Open with system default", for = "unix" }
]

[open]
rules = [
  { mime = "image/*", use = "swayimg" },
  { mime = "text/*",  use = "edit" },
  { mime = "*",       use = "open" }
]
