#[Backend]
backend = "auto"
transition_mode = "static"

#[Smoothing]
smoothing = true
startup_duration = 0.5       # Slow transition
shutdown_duration = 0.5
adaptive_interval = 1

#[Static configuration]
static_temp = 2333           # Very warm
static_gamma = 75            # Quite dim

